@startuml
participant 사용자 as User
participant Frontend
participant Backend

User -> Frontend: 이메일/비밀번호 찾기 페이지 진입

Frontend -> Backend: 1. 이메일 인증코드 요청 \n POST /api/v1/member-verification/email/send
Backend --> Frontend: HTTP 200 존재하는 사용자의 이메일인 경우, 이메일 인증코드 발송

Frontend -> Backend: 2. 이메일 인증 코드 확인 요청 \n /api/v1/member-verification/email/verify
Backend --> Frontend: HTTP 200 인증 성공한 경우, 비밀번호 재설정용 토큰 발급\n(해당 토큰은 비밀번호 재설정 시에만 사용 가능)

Frontend -> Backend: 3. 비밀번호 재설정 요청 \n PUT /api/v1/member-verification/password
Backend --> Frontend: HTTP 200 비밀번호 재설정 성공
@enduml